name: Update environment
description: Action to update the version of a service in an environment
inputs:
  ciToken:
    description: CI Github token
    required: true
  environment:
    description: Name of the environment
    required: true
  serviceName:
    description: Name of the service
    required: true
  sidecarServiceName:
    description: Name of the sidecar service
    required: false
  serviceVersion:
    description: Version of service
    required: true
runs:
  using: node12
  main: index.js
