name: Update environment

on:
  push:
    branches:
      - master

jobs:
  updateEnvironment:
    name: Update environment
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        id: release
        uses: codfish/semantic-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
